<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.5" />
    <ProjectReference Include="..\MediTrack.Core\MediTrack.Core.csproj" />
    <ProjectReference Include="..\MediTrack.Data\MediTrack.Data.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseAppHost>false</UseAppHost>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>

</Project>
